name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-notebook-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set image name (1)
        run: |
          echo "image_name=ucsb/pstat-134-234-winter2023" >> $GITHUB_ENV
          echo "$( echo ${{ github.sha }} | cut -c1-7 )"
          echo "short_sha=$( echo ${{ github.sha }} | cut -c1-7 )" >> $GITHUB_ENV
      - 
        name: Set image name (2)
        run: |
          echo "full_tag=${{ env.image_name }}:${{ env.short_sha }}" >> $GITHUB_ENV

      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./.devcontainer/
          platforms: linux/amd64
          push: true
          tags: ${{ env.full_tag }}